language: java
dist: xenial

services:
  - docker
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - graphviz

# skip default install command
install: true

script:
  - ./travis.sh
  - ./docker.sh build
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: target
    github_token:  $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./docker.sh deploy
    on:
      repo: schemaspy/schemaspy
      all_branches: true
  - provider: releases
    api_key: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    skip_cleanup: true
    file_glob: true
    file: target/schemaspy*.jar
    draft: true
    on:
      repo: schemaspy/schemaspy
      tags: true

